# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataobjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='dataobjects.Dataset'),
        ),
    ]
