# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataobjects', '0002_auto_20170510_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='_format',
            new_name='format',
        ),
    ]
