# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataobjects', '0002_auto_20161215_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.SlugField(unique=True),
        ),
    ]
