# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataobjects', '0003_auto_20161215_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
