language: python
python:
    - "2.7"
install:
    - pip install -U pip
    - pip install coveralls
    - pip install -r requirements.txt
script:
    - coverage run --source=dms,dataobjects manage.py test
after_success:
    - coveralls
